# Language-specific strings
de:
  title: Toolbox - School of Data CH
  tagline: Data Toolbox
  description: >
    Empfohlene Open Source Tools für den Umgang mit offenen Daten.
    Wir bieten auch Unterstützung über unser
    <a href="https://forum.schoolofdata.ch/categories">Forum</a>
    und organisieren projektbasierte
    <a href="https://schoolofdata.ch">Workshops</a>.
  signup:
    title: Empfehlen
    name: Name
    email: E-mail
    comment: Nachricht
    skills: Empfohlenes Niveau ..
    beginner: Anfanger
    intermediate: Erfahrenen
    advanced: Profi
    expert: Experten
    send: Senden
en:
  title: Toolbox - School of Data CH
  tagline: Data Toolbox
  description: >
    Recommended Open Source Tools for working with open data.
    You can seek advice on these through our
    <a href="https://forum.schoolofdata.ch/categories">Forum</a>
    and our the hands-on
    <a href="https://schoolofdata.ch">Workshops</a> we organise.
  signup:
    title: Recommend
    name: Name
    email: E-mail
    comment: Message
    skills: Skill level ..
    beginner: Beginner
    intermediate: Experienced
    advanced: Professional
    expert: Expert
    send: Send

# Toolbox categories
toolbox:
  categories:
    - name: ask
      title: Ask
      info:
        en: These tools can help to formulate good questions, which is key to finding good data.
        de: Diese Tools können dabei helfen, gute Fragen zu formulieren. Dies ist der Schlüssel zum Finden guter Daten.
    - name: find
      title: Find
      info:
        en: Searching and finding data that has already been released is easier with portals and agents.
        de: Das Suchen und Finden bereits veröffentlichter Daten ist mit Portalen und Agenten einfacher.
    - name: get
      title: Get
      info:
        en: Beyond file downloads, data is collected data in forms, mobile apps, scraping and aggregation.
        de: Neben Datei-Downloads werden Daten in Formularen, mobilen Apps, Scraping und Aggregation gesammelt.
    - name: verify
      title: Verify
      info:
        en: Tools to check authenticity and authority, completeness and consistency of datasets.
        de: Tools zur Überprüfung der Authentizität und Autorität, Vollständigkeit und Konsistenz von Datensätzen.
    - name: clean
      title: Clean
      info:
        en: Removing invalid entries, combining datasets, and doing any number of other normalizations.
        de: Entfernen ungültiger Einträge, Kombinieren von Datensätzen und Durchführen einer beliebigen Anzahl anderer Normalisierungen.
    - name: analyse
      title: Analyse
      info:
        en: Machines can do a lot of it, but working with data will always involve analytical work.
        de: Maschinen können selber vieles tun, aber die Arbeit mit Daten erfordert immer analytische Arbeit.
    - name: present
      title: Present
      info:
        en: Tools to package data in an appropriate way for the audiences we wish to aim it at.
        de: Tools, um Daten in geeigneter Weise für die Zielgruppen zu paketieren, auf die wir zielen wollen.

# Site links
title: School of Data Toolbox
region: Switzerland
url: "https://toolbox.schoolofdata.ch"
email: info@schoolofdata.ch
forum: "https://forum.schoolofdata.ch"
twitter: schoolofdata_ch
facebook: schoolofdata
github: schoolofdata-ch
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass

# Isotope settings
highlighter: rouge
exclude: [ minify.sh ]
