# Language-specific strings
en:
  title: Reviews - School of Data CH
  tagline: Datasets Review
  description: >
    Community examined datasets, which we also discuss on our
    <a href="https://forum.schoolofdata.ch/categories">Forum</a>
    and put to use in our
    <a href="https://schoolofdata.ch">Workshops</a>.
  signup:
    title: Contribute
    name: Name
    email: E-mail
    comment: Recommendation, with links to web pages with details.
    type: Type ..
    types:
      ogd: Open Government Data
      sci: Scientific Data
      crowd: Crowdsourced Data
      linked: Linked Data
    send: Send

# Site links
title: Data Reviews
region: Switzerland
url: "https://reviews.schoolofdata.ch"
email: info@schoolofdata.ch
forum: "https://forum.schoolofdata.ch"
twitter: schoolofdata_ch
facebook: schoolofdata
github: schoolofdata-ch
grecaptcha:
  key: 6Lco8A8UAAAAAH68UXg94Ib9ptw6fRGxnZtSb0oQ

# Build settings
baseurl: "" # the subpath, e.g. /blog
markdown: kramdown
sass:
  sass_dir: sass

# Isotope settings
highlighter: rouge
exclude: [ minify.sh ]
